// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "BackwardsGyroAuto.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

BackwardsGyroAuto::BackwardsGyroAuto(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void BackwardsGyroAuto::Initialize()//intializes variables for control during autonomous period
{
	//speed = Robot::drivetrain->GetPower();
	correction = Robot::drivetrain->GetkP();
	duration = Robot::drivetrain->GetAutoTime();
	delay = Robot::drivetrain->GetDelay();

	SetTimeout(duration+delay);

	Robot::drivetrain->ResetGyro();
	Wait(delay);
	Robot::wrist->DownWristState();

}

// Called repeatedly when this Command is scheduled to run
void BackwardsGyroAuto::Execute() {
	Robot::drivetrain->BackwardsAuto(.600, correction);
}

// Make this return true when this Command no longer needs to run execute()
bool BackwardsGyroAuto::IsFinished() {
    return IsTimedOut();
}

// Called once after isFinished returns true
void BackwardsGyroAuto::End() {
	Robot::drivetrain->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void BackwardsGyroAuto::Interrupted() {
	End();
}
