// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<Joystick> pad;
	std::shared_ptr<JoystickButton> padButton9;
	std::shared_ptr<JoystickButton> padButton8;
	std::shared_ptr<JoystickButton> padButton7;
	std::shared_ptr<JoystickButton> padButton6;
	std::shared_ptr<JoystickButton> padButton5;
	std::shared_ptr<JoystickButton> padButton3;
	std::shared_ptr<JoystickButton> padButton2;
	std::shared_ptr<JoystickButton> padButton1;
	std::shared_ptr<Joystick> joy;
	std::shared_ptr<JoystickButton> joyButton6;
	std::shared_ptr<JoystickButton> joyButton5;
	std::shared_ptr<JoystickButton> joyButton4;
	std::shared_ptr<JoystickButton> joyButton3;
	std::shared_ptr<JoystickButton> joyButton2;
	std::shared_ptr<JoystickButton> joyButton1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<Joystick> getJoy();
	std::shared_ptr<Joystick> getPad();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
